### ISSUE TITLE
user-management sql exception in test case

### ISSUE THREAD

**Issue by stevehu** [networknt/light-portal#55]
This might be my local environment issue but need someone else to confirm. 

```
11:29:21.735 [XNIO-6 task-1]  -F5xSiMzSKqsxGqDzqSUuw ERROR c.n.p.u.m.j.user.UserRepositoryImpl save - SqlException:
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'00000162a5e0472c-1e4f644144f00000' (USER_DETAIL: USER_ID BIGINT NOT NULL)"; SQL statement:
INSERT INTO user_detail (user_id, email, host, timezone, screen_name, first_name, last_name, gender, birthday, password_hash, password_salt, locale, confirmed, locked, deleted, createBy,  createdAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?, ?, ?, ?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17) [22018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.table.Column.convert(Column.java:156)
	at org.h2.command.dml.Insert.insertRows(Insert.java:144)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:158)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:144)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at com.networknt.portal.usermanagement.model.jdbc.user.UserRepositoryImpl.save(UserRepositoryImpl.java:352)
	at com.networknt.portal.usermanagement.model.auth.service.UserServiceImpl.store(UserServiceImpl.java:378)
	at com.networknt.portal.usermanagement.model.auth.service.UserServiceImpl.signup(UserServiceImpl.java:351)
	at com.networknt.portal.usermanagement.handler.UserPostHandler.handleRequest(UserPostHandler.java:43)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at com.networknt.validator.ValidatorHandler.handleRequest(ValidatorHandler.java:82)
	at com.networknt.sanitizer.SanitizerHandler.handleRequest(SanitizerHandler.java:87)
	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:150)
	at com.networknt.body.BodyHandler.handleRequest(BodyHandler.java:115)
	at com.networknt.swagger.SwaggerHandler.handleRequest(SwaggerHandler.java:95)
	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:70)
	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:64)
	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:72)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by chenyan71** [comment]
This issue has been fixed on previous release. The userId DB field is defined as varchar:

 user_id varchar(256)
